version: '3.1'

services:
  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: none

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data/mongodb:/data/db
    logging:
      driver: none

  yyets-web:
    image: bennythink/yyetsbot
    restart: unless-stopped
    environment:
      - mongo=mongo
      - redis=redis
    working_dir: /YYeTsBot/yyetsweb/
    command: [ "python3","server.py","-h=0.0.0.0" ]
    ports:
      - "8888:8888"

  socat:
    image: alpine/socat
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "socat", "tcp-listen:2375,fork,reuseaddr","unix-connect:/var/run/docker.sock" ]

  yyets-bot:
    image: bennythink/yyetsbot
    depends_on:
      - redis
      - socat
      - mongo
    restart: on-failure
    env_file:
      - env/yyets.env

  mailhog:
    image: cd2team/mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /home/photos:/usr/share/nginx/html/photos
      - ./certs/:/etc/nginx/certs/
      - ./logs:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Shanghai